/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 high_rise_building.glb 
*/

import React from "react";
import {
   useGLTF,
   // useTexture
} from "@react-three/drei";

export default function HighRiseBuilding(props) {
   const { nodes, materials } = useGLTF("/models/high_rise_building.glb");

   // const texture = useTexture("/images/building-texture.jpg");

   return (
      <group {...props} dispose={null}>
         <group position={[32.677, 12.236, 20.858]}>
            <mesh
               geometry={nodes.Object_17.geometry}
               material={materials.darkbeveled}
            />
            <mesh
               geometry={nodes.Object_18.geometry}
               material={materials.darkbeveled}
            />
         </group>
         <group position={[32.677, 12.236, 20.858]}>
            <mesh
               geometry={nodes.Object_22.geometry}
               material={materials.darkbeveled}
            />
            <mesh
               geometry={nodes.Object_23.geometry}
               material={materials.darkbeveled}
            />
         </group>
         <group position={[32.677, 12.236, 20.858]}>
            <mesh
               geometry={nodes.Object_29.geometry}
               material={materials.darkbeveled}
            />
            <mesh
               geometry={nodes.Object_30.geometry}
               material={materials.darkbeveled}
            />
         </group>
         <group position={[32.677, 12.236, 20.858]}>
            <mesh
               geometry={nodes.Object_36.geometry}
               material={materials.darkbeveled}
            />
            <mesh
               geometry={nodes.Object_37.geometry}
               material={materials.darkbeveled}
            />
         </group>
         <group position={[-0.023, 0.151, 20.774]}>
            <mesh
               geometry={nodes.Object_57.geometry}
               material={materials["m.ConcreteStone.001"]}
            />
            <mesh
               geometry={nodes.Object_58.geometry}
               material={materials["_Black.002"]}
            />
            <mesh
               geometry={nodes.Object_59.geometry}
               material={materials["m.GlassReal"]}
            />
         </group>
         <group position={[32.674, 136.336, 20.76]}>
            <mesh
               geometry={nodes.Object_65.geometry}
               material={materials["m.StoneTile"]}
            />
            <mesh
               geometry={nodes.Object_66.geometry}
               material={materials["m.DarkStoneTile.001"]}
            />
            <mesh
               geometry={nodes.Object_67.geometry}
               material={materials.metal}
            />
            <mesh
               geometry={nodes.Object_68.geometry}
               material={materials.metal}
            />
            <mesh
               geometry={nodes.Object_69.geometry}
               material={materials.Material}
            />
            <mesh
               geometry={nodes.Object_70.geometry}
               material={materials["m.DarkMatte"]}
            />
            <mesh
               geometry={nodes.Object_71.geometry}
               material={materials["_Black.001"]}
            />
         </group>
         <group position={[-32.798, 88.332, 20.806]}>
            <mesh
               geometry={nodes.Object_73.geometry}
               material={materials["_Black.001"]}
            />
            <mesh
               geometry={nodes.Object_74.geometry}
               material={materials["m.DarkStoneTile.001"]}
            />
            <mesh
               geometry={nodes.Object_75.geometry}
               material={materials.metal}
            />
            <mesh
               geometry={nodes.Object_76.geometry}
               material={materials.metal}
            />
            <mesh
               geometry={nodes.Object_77.geometry}
               material={materials.Material}
            />
            <mesh
               geometry={nodes.Object_78.geometry}
               material={materials["m.DarkMatte"]}
            />
            <mesh
               geometry={nodes.Object_79.geometry}
               material={materials["m.StoneTile"]}
            />
         </group>
         <group position={[32.687, 7.847, 20.854]}>
            <mesh
               geometry={nodes.Object_85.geometry}
               material={materials["AO.001"]}
            />
            <mesh
               geometry={nodes.Object_86.geometry}
               material={materials["AO.001"]}
            />
            <mesh
               geometry={nodes.Object_87.geometry}
               material={materials["AO.001"]}
            />
            <mesh
               geometry={nodes.Object_88.geometry}
               material={materials["AO.001"]}
            />
         </group>
         <group position={[-32.848, 8.236, 20.875]}>
            <mesh
               geometry={nodes.Object_90.geometry}
               material={materials["m.ConcreteStone.000"]}
            />
            <mesh
               geometry={nodes.Object_91.geometry}
               material={materials["m.DarkShine"]}
            />
            <mesh
               geometry={nodes.Object_92.geometry}
               material={materials.Glass_}
            />
            <mesh
               geometry={nodes.Object_93.geometry}
               material={materials["_Black.016"]}
            />
         </group>
         <group position={[32.683, 8.236, 20.838]}>
            <mesh
               geometry={nodes.Object_95.geometry}
               material={materials["m.ConcreteStone.000"]}
            />
            <mesh
               geometry={nodes.Object_96.geometry}
               material={materials["m.DarkShine"]}
            />
            <mesh
               geometry={nodes.Object_97.geometry}
               material={materials["m.GlassReal"]}
            />
            <mesh
               geometry={nodes.Object_98.geometry}
               material={materials["_Black.016"]}
            />
         </group>
         <mesh
            geometry={nodes.Object_5.geometry}
            material={materials._GlassReal}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.plaster}
            position={[32.677, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.plaster}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.darkbeveled}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_13.geometry}
            material={materials._GlassReal}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_15.geometry}
            material={materials._GlassReal}
            position={[32.677, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_20.geometry}
            material={materials.plaster}
            position={[32.677, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_25.geometry}
            material={materials._GlassReal}
            position={[32.677, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_27.geometry}
            material={materials.plaster}
            position={[32.677, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_32.geometry}
            material={materials._GlassReal}
            position={[32.677, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_34.geometry}
            material={materials.plaster}
            position={[32.677, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_39.geometry}
            material={materials._GlassReal}
            position={[32.677, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_41.geometry}
            material={materials.plaster}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_43.geometry}
            material={materials.darkbeveled}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_45.geometry}
            material={materials._GlassReal}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_47.geometry}
            material={materials.plaster}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_49.geometry}
            material={materials.darkbeveled}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_51.geometry}
            material={materials._GlassReal}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_53.geometry}
            material={materials.plaster}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_55.geometry}
            material={materials.darkbeveled}
            position={[-32.788, 12.236, 20.858]}
         />
         <mesh
            geometry={nodes.Object_61.geometry}
            material={materials["m.ConcreteStone.001"]}
            position={[-0.023, 0.151, 20.774]}
         />
         <mesh
            geometry={nodes.Object_63.geometry}
            material={materials["m.GeometricPattern01"]}
            position={[32.687, 7.847, 20.854]}
         />
         <mesh
            geometry={nodes.Object_81.geometry}
            material={materials.stone}
            position={[-0.023, 0.151, 20.774]}
         />
         <mesh
            geometry={nodes.Object_83.geometry}
            material={materials["AO.001"]}
            position={[32.687, 7.847, 20.854]}
         />
      </group>
   );
}

useGLTF.preload("/models/high_rise_building.glb");
